modLoader = "javafml"
loaderVersion = "[31,)"
#issueTrackerURL = ""
license = "Galacticraft Custom License"

[[mods]]
modId = "galacticraft"
version = "${version}"
displayName = "Galacticraft"
authors = "Team Galacticraft"
description = '''

'''
#logoFile = ""

[[dependencies.galacticraft]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.galacticraft]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.galacticraft]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"